# 
# ---
# Docker compose file for ranger stkac
#
# Nigel Jones - jonesn@uk.ibm.com
# ---

version: '2'
services:
  ranger-admin:
    build: ranger-admin
    ports: 
      - 6080:6080
      - 6182:6182
      - 6083:6083
      - 6183:6183
      - 8886:8886
    depends_on:
      - postgresdb
    links:
      - postgresdb
    networks:
      - trino-ranger-demo
    ulimits:
      nofile:
         soft: 4096
         hard: 4096
    volumes:
      - ./ranger-admin/install.properties:/root/install.properties
      - ./ranger-admin/docker-entrypoint.sh:/root/docker-entrypoint.sh
    #command: ["/bin/sh","-c","/opt/ranger-1.0.0-SNAPSHOT-admin/ranger-docker-start.sh"]
  postgresdb:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin99
      - POSTGRES_HOST_AUTH_METHOD=md5
    logging:
      options:
        max-size: 10m
        max-file: "3"
    build: postgresdb
    networks:
      - trino-ranger-demo
    command: ["postgres","-c","listen_addresses=*"]
    ports:
            - "15438:5438"
    volumes:
      - ranger-pg-data:/var/lib/postgresql/data
  trino:
    image: trinodb/trino:latest
    hostname: my-localhost-trino
    user: root
    container_name: my-localhost-trino
    entrypoint: /root/docker-entrypoint.sh
    networks:
      - trino-ranger-demo
    volumes:
      - ./trino/install.properties:/root/install.properties
      - ./trino/docker-entrypoint.sh:/root/docker-entrypoint.sh
    ports:
      - 8080:8080
networks:
  trino-ranger-demo:
    driver: bridge
volumes:
  ranger-pg-data: