apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-mariadb-deployment
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ranger-mariadb-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ranger-mariadb-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ranger-mariadb-service

    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin99
        image: "{{ .Values.image.mariadb.repository }}:{{ .Values.image.mariadb.tag }}"
        ImagePullPolicy: Always
        name: {{ .Chart.Name }}-mariadb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
