apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-postgresdb-deployment
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ranger-postgresdb-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ranger-postgresdb-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ranger-postgresdb-service

    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: Admin99
        - name: POSTGRES_HOST_AUTH_METHOD
          value: md5
        image: "{{ .Values.image.postgresdb.repository }}:{{ .Values.image.postgresdb.tag }}"
        ImagePullPolicy: Always
        name: {{ .Chart.Name }}-postgresdb
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
