# Default values for ranger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  ranger:
    repository: rubelw/ranger-docker-ranger-admin
    tag: latest
    pullPolicy: IfNotPresent

  postgresdb:
    repository: rubelw/ranger-docker-postgresdb
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

# Network configuration
service:
  #LoadBalancer is another option (not for IBM Cloud free cluster)
  type: NodePort



